# Generated by Django 6.0 on 2025-12-22 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("company_name", models.CharField(blank=True, max_length=100)),
                ("sector", models.CharField(blank=True, max_length=50)),
                ("exchange", models.CharField(default="NASDAQ", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open_price", models.FloatField()),
                ("high_price", models.FloatField()),
                ("low_price", models.FloatField()),
                ("close_price", models.FloatField()),
                ("adjusted_close_price", models.FloatField()),
                ("volume", models.BigIntegerField()),
                ("dividends", models.FloatField(default=0.0)),
                ("stock_splits", models.FloatField(default=0.0)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("stock", "date")},
            },
        ),
    ]
